### PR TITLE
fix: attempt to use `DallasTemperature.h` for temperature readings

### PR DESCRIPTION
**Pull request by Chris1320**
**UNTESTED CODE**

-----

Baka pwede yung `DallasTemperature.h` library?

### CODE REVIEW

**Review by YuKARLO15 — COMMENTED** [review]
Noted, will test the proposed changes tomorrow upon further review. Hardware is not on my possession so testing would not be possible until tomorrow.

**Comment by YuKARLO15** [comment]
> **UNTESTED CODE**
> 
> Baka pwede yung `DallasTemperature.h` library?

Okiii, testingin namin bukas, hehehe thankssss! <3

**Comment by YuKARLO15** [comment]
> > **UNTESTED CODE**
> > Baka pwede yung `DallasTemperature.h` library?
> 
> Okiii, testingin namin bukas, hehehe thankssss! <3

Will work with any sensor naman noh? LM35 gamit namin for the temp

**Comment by Chris1320** [comment]
Ooh, tinignan ko lang online yung kamukha ng gamit niyo. Not sure if supported ng library ang LM35. Close mo nalang itong PR if not compatible.

**Comment by YuKARLO15** [comment]
Pull request accepted

**Pull request merged**
